# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6c564bc1-c84c-4ac2-a535-97f3017c687f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-faa8517d-2a95-44bd-8623-5ed91f4cf1a8".device = "/dev/disk/by-uuid/faa8517d-2a95-44bd-8623-5ed91f4cf1a8";
  boot.initrd.luks.devices."luks-a36bd82a-156c-4388-a5ec-39f82206b1a1".device = "/dev/disk/by-uuid/a36bd82a-156c-4388-a5ec-39f82206b1a1";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2D39-6CBD";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4174ccb1-9ff2-4d12-825e-3998f1d24c4f"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
